#!/bin/sh

######################################################################
#
# REV - A POSIX Compatible Implementation Of The "rev" Command
#       Also Works On Just A POSIX Environment
#
# USAGE: rev [--by-myself] [filename ...]
#
#        --by-myself .... (write as the 1st argument when use)
#                         Not use the "built-in" rev command and always
#                         do seq by myself but it is inferior to the
#                         built-in in performance
#                         with leading zeros.
#
# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-08-09
#
# This is a public-domain software (CC0). It means that all of the
# people can use this for any purposes with no restrictions at all.
# By the way, We are fed up with the side effects which are brought
# about by the major licenses.
#
######################################################################


######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C
type command >/dev/null 2>&1 && type getconf >/dev/null 2>&1 &&
export PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
export UNIX_STD=2003  # to make HP-UX conform to POSIX

# === Define the functions for printing usage and error message ======
print_usage_and_exit () {
  cat <<-USAGE 1>&2
	Usage   : ${0##*/} [--by-myself] [filename ...]
	Arg&Opts: Almost compatible with the original rev command
	          But --by-myself is the only original option, it prevent
	          from use the built-in same name command even if available
	Version : 2017-08-09 16:52:29 JST
	          (POSIX Bourne Shell/POSIX commands)
	            * Although the bult-in rev produces better performance
	              than the POSIX commands set
	USAGE
  exit 1
}
error_exit() {
  ${2+:} false && echo "${0##*/}: $2" 1>&2
  exit $1
}
warning() {
  ${1+:} false && echo "${0##*/}: $1" 1>&2
}

# === Exec the built-in rev command if OK and exists =================
by_myself=0
case "${1:-}" in 
  '--by-myself')
     shift; by_myself=1
     ;;
  *) export mydir=$(d=${0%/*}/;[ "_$d" = "_$0/" ]||cd "$d";echo "$(pwd)")
     path0=${PATH:-}
     PATH=$(printf  '%s\n' "$path0"                |
            tr      ':' '\n'                       |
            awk     '$0!=ENVIRON["mydir"]{print;}' |
            tr      '\n' ':'                       |
            grep -v '^:$'                          |
            sed     's/:$//'                       )
     CMD_builtin=$(command -v rev 2>/dev/null || :)
     case "$CMD_builtin" in '') by_myself=1;; esac
     PATH=$path0
     unset mydir
     ;;
esac
case $by_myself in 0) exec "$CMD_builtin" ${1+"$@"}; exit 1;; esac


######################################################################
# Argument Parsing and Reversing
######################################################################

# === print help if requested ========================================
case "${1:-}" in -h|-v|--help|--version) print_usage_and_exit;; esac

# === do it ==========================================================
awk 'BEGIN { ORS="";                                               }
     { for(i=length($0);i>0;i--){print substr($0,i,1);} print "\n";}' ${1+"$@"}


######################################################################
# Finish
######################################################################

exit 0
