#!/bin/sh

######################################################################
#
# UNESCOCT - A Filter of Unescaping Escaped 3-Digit-Octal Numbers
#
# USAGE: unescoct <file> [file...]
#
# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-02-25
#
# This is a public-domain software (CC0). It means that all of the
# people can use this for any purposes with no restrictions at all.
# By the way, I am fed up the side effects which are broght about by
# the major licenses.
#
######################################################################


######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C
export PATH="$(command -p getconf PATH)${PATH:+:}${PATH:-}"

# === Define the functions for printing usage ========================
print_usage_and_exit () {
  cat <<-USAGE 1>&2
	Usage   : ${0##*/} <file> [file...]
	Version : 2017-02-25 21:55:53 JST
	USAGE
  exit 1
}


######################################################################
# Argument Parsing
######################################################################

# === Print usage and exit if one of the help options is set =========
case "$# ${1:-}" in
  '1 -h'|'1 --help'|'1 --version') print_usage_and_exit;;
esac

# === Set "-" into the 1st argument if no argument is given ==========
case $# in 0) set -- -;; esac


######################################################################
# Main
######################################################################

(cat /dev/null "$@"; echo '')                                   |
awk 'BEGIN {                                                    #
       OFS=""; ORS="";                                          #
       while (getline line) {                                   #
         while (1) {                                            #
           if (line=="") {print "\n"; break;}                   #
           if (match(line,/\\[0-9][0-9][0-9]/)) {               #
             print substr(line, 1, RSTART-1);                   #
             o=substr(line,RSTART+1,3);                         #
             n=substr(o,1,1)*64+substr(o,2,1)*64+substr(o,3,1); #
             printf("%c",n);                                    #
             line=substr(line,RSTART+4);                        #
           } else {                                             #
             print line                                         #
             line="";                                           #
           }                                                    #
         }                                                      #
       }                                                        #
     }'                                                         |
awk 'BEGIN{                                                     #
       ORS=""; OFS="";                                          #
       getline line;                                            #
       print line;                                              #
       dlm=sprintf("\n");                                       #
       while (getline line) {                                   #
         print dlm,line;                                        #
       }                                                        #
     }'
